[Feature] Roles and Permissions
canyongbs/assistforhighered-2 pull request #13
Opened 2023-07-14 17:51 UTC by dgoetzit

This PR introduces Roles and Permissions, facilitated in the app via the Spatie/Laravel-permission package. I've added some documentation to cover the high level convention, and there is some more work to be done here regarding:

1. Role Groups
2. One-off processes to migrate new roles/permissions without impacting existing data in an app
3. Determining all of the necessary permissions per model and custom permissions currently needed in the application

2023-07-15 01:47 UTC, Orrison requested changes
Looks great! I just had a few questions. There are also some merge conflicts.

2023-07-15 01:47 UTC, Orrison commented on app/Models/Permission.php
> +    use DefinesPermissions;
Is this perhaps one that should be overwritten? Since we would really only ever want the `index` and `show` permission for this?

2023-07-15 01:47 UTC, Orrison commented on app/Models/Concerns/DefinesPermissions.php
How do you feel about `HasPermissions`? That seems to be the common convention for a lot of these traits.

2023-07-15 01:47 UTC, Orrison commented on config/permissions/api/custom.php
> +    'role.access',
Curious if you think these could be deleted now, as they should be covered by the Model trait?

2023-07-15 01:47 UTC, Orrison commented on config/permissions/web/custom.php
> +    'role.access',
Same questions as the `api` one.

2023-07-15 01:47 UTC, Orrison commented on config/roles/api/super_admin.php
We may have talked about this already. Sorry if so.

Do we need this since the Super Admin's access in implicit?

2023-07-15 01:47 UTC, Orrison commented on docs/roles-and-permissions.md
> +The application uses a dedicated convention in order to define and poulate roles and permissions, leaving little in the way of thinking when it comes time to stand up the application locally or in a
```suggestion
The application uses a dedicated convention in order to define and populate roles and permissions, leaving little in the way of thinking when it comes time to stand up the application locally or in a live environment.
```

2023-07-16 00:39 UTC, dgoetzit commented on app/Models/Concerns/DefinesPermissions.php
I only didn't do this as Spatie also has a `HasPermissions` trait, and didn't want to cause any confusion.

2023-07-16 00:42 UTC, dgoetzit commented on config/roles/api/super_admin.php
We could do without it, but right now the convention in place will create a role for every configuration file that exists in the `roles` directory. So it's not necessary, but we'd need to make a minor adjustment to the `CreateRoles` action.

2023-07-18 02:41 UTC, Orrison approved these changes

2023-07-18 02:42 UTC, merged