[ASSIST-425] & [ASSIST-369]
canyongbs/assistforhighered-2 pull request #94
Opened 2023-09-15 18:37 UTC by Orrison

2023-09-17 20:05 UTC, dgoetzit requested changes
Looks good! Just a few suggestions for consistency.

2023-09-17 20:05 UTC, dgoetzit commented on app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/CreateProspect.php
> +                TextInput::make('full_name')
```suggestion
                TextInput::make(Prospect::displayNameKey())
```

2023-09-17 20:05 UTC, dgoetzit commented on app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ViewProspect.php
> +                        TextEntry::make('full_name')
```suggestion
                        TextEntry::make(Prospect::displayNameKey())
```

2023-09-18 13:16 UTC, Orrison commented on app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/EditProspect.php
> +                TextInput::make('full_name')
Fixed

2023-09-18 13:17 UTC, Orrison commented on app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/CreateProspect.php
> +                TextInput::make('full_name')
Fixed

2023-09-18 13:17 UTC, Orrison commented on app-modules/prospect/src/Filament/Resources/ProspectResource/Pages/ViewProspect.php
> +                        TextEntry::make('full_name')
Fixed

2023-09-18 13:25 UTC, dgoetzit approved these changes

2023-09-18 13:51 UTC, merged